# Generated by Django 4.1.1 on 2022-11-07 13:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_reviewrating_is_random_choice'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='player',
            options={'ordering': ['id'], 'verbose_name': 'Best fantasy players', 'verbose_name_plural': 'Best fantasy players'},
        ),
        migrations.AlterModelOptions(
            name='reviewrating',
            options={'ordering': ['id'], 'verbose_name': 'Voting', 'verbose_name_plural': 'Voting'},
        ),
        migrations.AlterField(
            model_name='reviewrating',
            name='body_strength',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='reviewrating',
            name='health',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='reviewrating',
            name='speed',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='reviewrating',
            name='strength_environment',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='reviewrating',
            name='talent',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
